package com.exe101.backend.model;

public enum OrderStatus {
    DRAFT,
    WAITING_DEPOSIT,
    DEPOSIT_PAID,
    PURCHASED,
    SHOP_SHIPPING,
    CHINA_WAREHOUSE,
    INTERNATIONAL_SHIPPING,
    VIETNAM_WAREHOUSE,
    WAITING_FINAL_PAYMENT,
    FINAL_PAID,
    DELIVERING,
    COMPLETED,
    CANCELLED,
    RETURN_REQUESTED,
    REFUNDED
}
