spring:
  application:
    name: backend
  datasource:
    url: ${DB_URL:jdbc:mysql://localhost:3306/exe101_backend?createDatabaseIfNotExist=true&useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=Asia/Ho_Chi_Minh}
    username: ${DB_USERNAME:root}
    password: ${DB_PASSWORD:Hoangle300501@}
    driver-class-name: ${DB_DRIVER:com.mysql.cj.jdbc.Driver}
  jpa:
    database-platform: org.hibernate.dialect.MySQLDialect
    hibernate:
      ddl-auto: ${JPA_DDL_AUTO:update}
    open-in-view: false
    show-sql: false
  h2:
    console:
      enabled: false

  data:
    redis:
      host: localhost
      port: 6379

  mail:
    host: smtp.gmail.com
    port: 587
    username: "yufiz.system@gmail.com"
    password: "grqhmqcqcofweukx"
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
            
server:
  port: 8080

app:
  exchange-rate:
    refresh-ms: 1800000
    initial-delay-ms: 10000
